apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-service:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: postgres.hello-resources.svc.cluster.local
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: mypassword
          ports:
            - containerPort: 8000