# service-app.yaml -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-system-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/solidity-software/app-store-example.git
    targetRevision: main
    path: repos/tenant-deploy-repo/app-store-apps/system
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
