apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: shared-postgres-secret
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: shared-postgres-secret
  namespaceSelector:
      matchNames:
        - hello-api
        - hello-system
  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore    
    target:
      name: shared-postgres-secret
      creationPolicy: 'Owner'
    dataFrom:
      - extract: 
          key: generated-secret