apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: hello-resources        
      server:
        url: "https://kubernetes.default"  
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-sa
          namespace: external-secrets        