apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    kubernetes:
      server:
        url: ""  # Leave empty to use the in-cluster API
      auth:
        serviceAccount:
          name: external-secrets-sa  # Ensure this service account has the necessary permissions
          namespace: external-secrets