apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: hello-resources
  name: shared-postgres-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  externalSecretName: shared-postgres-secret
  externalSecretSpec:
    dataFrom:
      - extract:
          key: generated-secret
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secret-store
    target:
      name: shared-postgres-secret
      creationPolicy: Owner
      deletionPolicy: Retain
  namespaceSelector:
    matchNames:
      - hello-api
      - hello-system
