apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: copy-secret
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: copy-secret-es
  namespaceSelectors:
  - matchLabels: {} #deploy to every namespace  
  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore    
    target:
      name: copy-secret
      creationPolicy: 'Owner'
    dataFrom:
      - extract: 
          key: generated-secret