apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password  
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: shared-postgres-secret
  data: 
    - secretKey: gpostgres-password
      remoteRef:
        key: generated-secret
        property: postgres-password
        metadataPolicy: None
