apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
        - name: wait-for-secret
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              while [ ! -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; do
                echo "Waiting for Kubernetes service account token..."
                sleep 1
              done
              while ! kubectl get secret shared-postgres-secret -n hello-resources; do
                echo "Waiting for secret 'shared-postgres-secret'..."
                sleep 2
              done
      containers:
        - name: fastapi
          image: fastapi-service:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: postgres.hello-resources.svc.cluster.local
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-postgres-secret
                  key: password
          ports:
            - containerPort: 8000