apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: webapp-ingress
  namespace: default
spec:
  http:
    - name: webapp-route
      match:
        hosts:
          - webapp.hello-cluster.com
        paths:
          - /*
      backends:
        - serviceName: hello-webapp
          servicePort: 5000