apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix
    targetRevision: latest
    helm:
      releaseName: apisix
      values: |
        gateway:
          type: NodePort
        ingress-controller:
          enabled: true
          config:
            apisix:
              serviceNamespace: ingress-apisix
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
