apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix-ingress-controller
    targetRevision: 1.7.0   # Use the latest stable version
    helm:
      releaseName: apisix-ingress-controller
      values: |
        config:
          ingressController:
            enableApisixDashboard: true
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true