apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: generated-secret
  namespace: default
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: generated-secret
    creationPolicy: Owner
    immutable: true
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dummy  # Required, even if unused
        property: unused
      generator:
        password:
          length: 20
          symbols: false
